services:
  nodes-check:
    build: .
    container_name: nodes-check
    restart: unless-stopped
    ports:
      - "18808:18808"
    volumes:
      - ./configs:/app/configs
      - ./runtime:/app/runtime
    command: ["/app/nodes-check", "-config", "/app/configs/config.example.yaml"]
